### PR TITLE
added documentation on Response objects

### PR DESCRIPTION
**Pull request by PommeVerte**
On a side note, I was wondering if it wouldn't be a good idea to have a docs folder in spider/spider. This would allow us to build the guide and api together and to have links from the guide to the api and vice/versa. Might be worth checking [yiisoft/yii2-apidoc](https://github.com/yiisoft/yii2-apidoc) (though I'm sure there are a billion other options)

It also makes it easier to add the documentation to a PR.

### CODE REVIEW

**Comment by chrismichaels84** [comment]
I am currently looking into a few options for documentation. I'm not a big fan of Yii, and don't really want to add it as a dependency for documentation. The end-goal is to have documentation guides, api documentation, and the "marketing site" under one roof. Eventually, it would make sense to keep the guides documentation under spider/spider, absolutely

But for now, I just wanted to get something up on readthedocs, which uses mkdocs and (for whatever reason), I've had a lot of problem using read the docs with repos that are not dedicated to documentation.

Another member of my team is helping with adding a "guides" feature to [Sami](https://github.com/FriendsOfPHP/Sami) which is used by Laravel and Symfony but doesn't require a full framework to work. The other great thing about Sami is that it can use remote github repos to make the api documentation.

I think what will eventually happen is for spider/spider to have a `/docs` or `/guides` folder with this documentation. And the `spider/docs` repo to have the Sami install and marketing site. When built, the spider/docs repo will scan spider/spider to build api documentation and compile the guides into one, sleek, twig-empowered website.

Eventually, lol.

**Comment by chrismichaels84** [comment]
In any case, this documentation looks great!

**Comment by PommeVerte** [comment]
Hey, dunno if it was on purpose or not but you didn't merge this. 
If it was on purpose just ignore me ;p

**Comment by chrismichaels84** [comment]
My bad. Thanks

**Pull request merged**
